Repository redhat-developer/intellij-openshift-connector, pull requests merged in 2023-10, with the labels that each got.

#588 fix: Update odo to 3.15.0
  src/main/resources/tools.json
Labels: lgtm

#583 feat: display 'creating...' while component is being created (#552)
  build.gradle
  src/main/java/org/jboss/tools/intellij/openshift/actions/ActionUtils.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/NodeUtils.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/OdoAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/binding/DeleteBindingAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/cluster/AboutAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/cluster/ListComponentsAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/cluster/ListServicesAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/cluster/LoginAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/cluster/RefreshAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/component/CreateComponentAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/component/DebugComponentAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/component/DeleteComponentAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/component/DescribeComponentAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/component/FeatureComponentAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/component/ImportComponentAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/component/LinkComponentAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/component/LinkServiceAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/component/ShowLogComponentAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/project/CreateProjectAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/project/DeleteProjectAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/registry/CreateRegistryAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/registry/DeleteRegistryAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/service/CreateServiceAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/service/DeleteServiceAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/service/DescribeServiceAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/service/LinkComponentAction.java
  src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationsRootNode.java
  src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationsTreeStructure.java
  src/main/java/org/jboss/tools/intellij/openshift/tree/application/ParentableNode.java
  src/main/java/org/jboss/tools/intellij/openshift/tree/application/ProcessingNode.java
  src/main/java/org/jboss/tools/intellij/openshift/tree/application/StructureAwareNode.java
  src/test/java/org/jboss/tools/intellij/openshift/actions/cluster/ListComponentsActionTest.java
  src/test/java/org/jboss/tools/intellij/openshift/tree/application/ProcessingNodeImplTest.java
Labels: lgtm, approve

#589 fix: dont NPE if initializing odo fails (#536)
  src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliTest.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/OdoAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/OpenGettingStartedAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/binding/DeleteBindingAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/binding/ShowBindingDetailsAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/cluster/AboutAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/cluster/LoginAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/cluster/OpenConsoleAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/component/CreateComponentAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/component/DebugComponentAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/component/DeleteComponentAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/component/DescribeComponentAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/component/FeatureComponentAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/component/FollowLogComponentAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/component/ImportComponentAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/component/LinkComponentAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/component/LinkServiceAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/component/ShowLogComponentAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/project/CreateProjectAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/project/DeleteProjectAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/registry/CreateRegistryAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/registry/DeleteRegistryAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/service/CreateServiceAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/service/DeleteServiceAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/service/DescribeServiceAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/service/LinkComponentAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/url/OpenInBrowserAction.java
  src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationRootNodeOdo.java
  src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationsRootNode.java
  src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationsTreeStructure.java
  src/main/java/org/jboss/tools/intellij/openshift/utils/odo/Component.java
  src/main/java/org/jboss/tools/intellij/openshift/utils/odo/ComponentFeatures.java
  src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliFactory.java
  src/test/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationRootNodeOdoTest.java
  src/test/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationTreeModelConfigUpdateTest.java
Labels: lgtm, approve

#587 chore: bump to latest IC version
  build.gradle
  gradle.properties
Labels: lgtm

#596 feat: Change job trigger to pull_request_target
  .github/workflows/ci.yml
Labels: enhancement, lgtm

#598 feat: Added UI tests job workflow for GA
  .github/workflows/ci.yml
  idea_license_token/idea.key.gpg
Labels: enhancement, lgtm
