Repository redhat-developer/intellij-openshift-connector, pull requests merged in 2023-11, with the labels that each got.

#606 chore: extract integration tests in their own workflow
  .github/workflows/ci.yml
  .github/workflows/integration_tests.yml
Labels: lgtm

#597 fix: fix build for next IJ version and fix Sonar coverage, bumping gradle
  .github/workflows/validate_IJ_versions.yml
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/main/java/org/jboss/tools/intellij/openshift/actions/component/CreateComponentAction.java
  src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationRootNodeOdo.java
  src/main/java/org/jboss/tools/intellij/openshift/ui/component/CreateComponentModel.java
  src/test/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationTreeModelConfigUpdateTest.java
Labels: lgtm, approve

#599 fix: can't connect to a cluster with private certificate
  .github/workflows/validate_IJ_versions.yml
  build.gradle
  src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCli.java
  src/main/resources/META-INF/plugin.xml
Labels: lgtm, approved

#610 fix: refreshing tree upon config change or kubeconfig removal (#595)
  build.gradle
  src/it/java/org/jboss/tools/intellij/openshift/utils/ToolFactoryTest.java
  src/it/java/org/jboss/tools/intellij/openshift/utils/helm/HelmCliTest.java
  src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliTest.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/NodeUtils.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/cluster/RefreshAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/component/LinkServiceAction.java
  src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationRootNodeOdo.java
  src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationsRootNode.java
  src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationsTreeStructure.java
  src/main/java/org/jboss/tools/intellij/openshift/tree/application/BaseNode.java
  src/main/java/org/jboss/tools/intellij/openshift/tree/application/BindingNode.java
  src/main/java/org/jboss/tools/intellij/openshift/tree/application/ChartReleaseNode.java
  src/main/java/org/jboss/tools/intellij/openshift/tree/application/ComponentNode.java
  src/main/java/org/jboss/tools/intellij/openshift/tree/application/CreateComponentLinkNode.java
  src/main/java/org/jboss/tools/intellij/openshift/tree/application/DescriptorFactory.java
  src/main/java/org/jboss/tools/intellij/openshift/tree/application/DevfileRegistriesNode.java
  src/main/java/org/jboss/tools/intellij/openshift/tree/application/DevfileRegistryComponentTypeNode.java
  src/main/java/org/jboss/tools/intellij/openshift/tree/application/DevfileRegistryComponentTypeStarterNode.java
  src/main/java/org/jboss/tools/intellij/openshift/tree/application/DevfileRegistryNode.java
  src/main/java/org/jboss/tools/intellij/openshift/tree/application/MessageNode.java
  src/main/java/org/jboss/tools/intellij/openshift/tree/application/NamespaceNode.java
  src/main/java/org/jboss/tools/intellij/openshift/tree/application/ParentableNode.java
  src/main/java/org/jboss/tools/intellij/openshift/tree/application/ProcessingNode.java
  src/main/java/org/jboss/tools/intellij/openshift/tree/application/ServiceNode.java
  src/main/java/org/jboss/tools/intellij/openshift/tree/application/URLNode.java
  src/main/java/org/jboss/tools/intellij/openshift/utils/ExceptionUtils.java
  src/main/java/org/jboss/tools/intellij/openshift/utils/ToolFactory.java
  src/main/java/org/jboss/tools/intellij/openshift/utils/odo/Odo.java
  src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCli.java
  src/test/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationTreeModelConfigUpdateTest.java
Labels: lgtm, approved
