Repository redhat-developer/intellij-openshift-connector, pull requests merged in 2024-10, with the labels that each got.

#920 fix: replaced helm png by svg, use resized, not scaled icon (#874)
  src/main/java/org/jboss/tools/intellij/openshift/tree/application/DescriptorFactory.java
  src/main/java/org/jboss/tools/intellij/openshift/ui/helm/ChartIcons.java
  src/main/resources/images/helm/helm.png
  src/main/resources/images/helm/helm.svg
Labels: lgtm, approved

#923 fix: readme: removed cdk, minishift. renamed CRC to OpenShift Local (…
  README.md
Labels: documentation, lgtm, approved

#930 fix: hookup 'install' button to return-key once button was created (#927)
  src/main/java/org/jboss/tools/intellij/openshift/ui/helm/install/InstallPanel.java
Labels: lgtm, approved

#928 fix: made sure telemetry sender is initialized (#926)
  src/main/java/org/jboss/tools/intellij/openshift/actions/HelmAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/helm/RemoveRepositoriesAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/helm/UninstallReleaseAction.java
Labels: approved

#940 fix: remove IU requirement and drop remote javascript debug
  build.gradle
  gradle.properties
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/junit/TestRunnerExtension.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/component/DebugNodeJSComponentAction.java
  src/main/resources/META-INF/plugin.xml
  src/main/resources/META-INF/withJavaScriptDebugger.xml
  src/test/java/org/jboss/tools/intellij/openshift/actions/component/DebugNodeJSComponentActionTest.java
Labels: lgtm, approved

#933 test: disable service tests
  .github/workflows/ci.yml
  .github/workflows/cluster_integration_ui_tests.yml
  .github/workflows/public_integration_ui_tests.yml
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/AbstractBaseTest.java
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/ClusterTestsSuite.java
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/PublicTestsSuite.java
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/common/CreateComponentFixture.java
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/common/ImportProjectFromVersionControlFixture.java
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/common/ProjectTreeFixture.java
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/common/WelcomeDialogFixture.java
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/dialogs/ClusterLoginDialog.java
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/dialogs/cluster_project/ChangeProjectDialog.java
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/dialogs/cluster_project/CreateNewProjectDialog.java
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/dialogs/cluster_project/DeleteProjectDialog.java
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/dialogs/component/CreateComponentDialog.java
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/dialogs/service/CreateNewServiceDialog.java
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/tests_cluster/AboutClusterTest.java
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/tests_cluster/AbstractClusterTest.java
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/tests_cluster/CreateComponentTest.java
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/tests_cluster/CreateServiceTest.java
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/tests_cluster/ProjectClusterTest.java
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/tests_public/AboutPublicTest.java
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/tests_public/ClusterLoginDialogPublicTest.java
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/tests_public/GettingStartedTest.java
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/tests_public/OpenshiftExtensionTest.java
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/utils/CleanUpUtility.java
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/utils/KubeConfigUtility.java
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/utils/ProjectUtility.java
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/utils/constants/XPathConstants.java
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/views/GettingStartedView.java
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/views/OpenshiftView.java
  src/it/java/org/jboss/tools/intellij/openshift/utils/helm/HelmCliRepoTest.java
  src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliComponentTest.java
  src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliServiceTest.java
  src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliTest.java
Labels: lgtm, approved

#894 chore: support IJ 2024.2
  .github/workflows/IJ-latest.yml
  .github/workflows/cluster_integration_ui_tests.yml
  .github/workflows/no_context_integration_ui_tests.yml
  .github/workflows/validate_IJ_versions.yml
  Jenkinsfile
  build.gradle
  build.gradle.kts
  gradle.properties
  gradle/libs.versions.toml
  idea_license_token/idea.key.gpg
  settings.gradle.kts
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/dialogs/ClusterLoginDialog.java
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/dialogs/cluster_project/ChangeProjectDialog.java
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/tests_cluster/CreateServiceTest.java
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/views/GettingStartedView.java
  src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliComponentTest.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/component/CreateComponentAction.java
  src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationRootNodeOdo.java
  src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationsRootNode.java
  src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCli.java
  src/main/java/org/jboss/tools/intellij/openshift/utils/odo/SchemaHelper.java
  src/main/resources/META-INF/plugin.xml
  src/test/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationRootNodeOdoTest.java
  src/test/java/org/jboss/tools/intellij/openshift/ui/sandbox/SandboxRegistrationServerMock.java
Labels: lgtm, approved
