Repository redhat-developer/intellij-openshift-connector, pull requests merged in 2024-07, with the labels that each got.

#865 feat: added Refresh action for helm repositories tree node (#808)
  src/main/java/org/jboss/tools/intellij/openshift/actions/cluster/LoginAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/cluster/RefreshAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/helm/RefreshAction.java
  src/main/resources/META-INF/plugin.xml
Labels: lgtm, approved

#867 test: added test for RefreshAction for helm repositories (#808)
  src/test/java/org/jboss/tools/intellij/openshift/actions/helm/RefreshActionTest.java
Labels: lgtm, approved

#872 fix: removed usage of PopupHandlerAdapter
  src/main/java/org/jboss/tools/intellij/openshift/WindowToolFactory.java
Labels: enhancement, lgtm, approved

#873 fix: make sure ApplicationsRootNode is properly disposed (#868)
  src/main/java/org/jboss/tools/intellij/openshift/WindowToolFactory.java
  src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationsRootNode.java
  src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationsTreeStructure.java
  src/test/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationTreeModelConfigUpdateTest.java
Labels: lgtm, approved

#582 test: Added integration UI test cases
  .github/workflows/cluster_integration_ui_tests.yml
  .github/workflows/public_integration_ui_tests.yml
  build.gradle
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/AbstractBaseTest.java
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/BaseUITest.java
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/ClusterTestsSuite.java
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/Jenkinsfile
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/PublicTestsSuite.java
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/dialogs/ClusterLoginDialog.java
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/dialogs/ProjectStructureDialog.java
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/dialogs/cluster_project/ChangeProjectDialog.java
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/dialogs/cluster_project/CreateNewProjectDialog.java
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/dialogs/cluster_project/DeleteProjectDialog.java
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/dialogs/component/CreateComponentDialog.java
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/dialogs/service/CreateNewServiceDialog.java
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/tests_cluster/AboutClusterTest.java
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/tests_cluster/AbstractClusterTest.java
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/tests_cluster/CreateComponentTest.java
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/tests_cluster/CreateServiceTest.java
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/tests_cluster/LoginClusterTest.java
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/tests_cluster/ProjectClusterTest.java
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/tests_public/AboutPublicTest.java
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/tests_public/ClusterLoginDialogPublicTest.java
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/tests_public/GettingStartedTest.java
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/tests_public/OpenshiftExtensionTest.java
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/utils/CleanUpUtility.java
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/utils/KubeConfigUtility.java
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/utils/constants/LabelConstants.java
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/utils/constants/XPathConstants.java
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/views/GettingStartedView.java
  src/it/java/org/jboss/tools/intellij/openshift/test/ui/views/OpenshiftView.java
Labels: tests, lgtm, approved

#856 fix: Anonymise error messages by removing exception handling
  src/main/java/org/jboss/tools/intellij/openshift/actions/HelmAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/TelemetryAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/binding/DeleteBindingAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/cluster/AboutAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/cluster/LoginAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/cluster/OpenConsoleAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/component/CreateComponentAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/component/DebugComponentAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/component/DeleteComponentAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/component/DescribeComponentAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/component/FeatureComponentAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/component/ImportComponentAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/component/LinkComponentAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/component/LinkServiceAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/component/ShowLogComponentAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/helm/RefreshAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/helm/RemoveRepositoriesAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/project/CreateProjectAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/project/DeleteProjectAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/registry/CreateRegistryAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/registry/DeleteRegistryAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/service/CreateServiceAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/service/DeleteServiceAction.java
  src/main/java/org/jboss/tools/intellij/openshift/actions/service/LinkComponentAction.java
  src/main/java/org/jboss/tools/intellij/openshift/telemetry/TelemetryHandler.java
  src/main/java/org/jboss/tools/intellij/openshift/telemetry/TelemetrySender.java
Labels: lgtm, approved

#879 fix: Fix usage of deprecated APIs
  src/main/java/org/jboss/tools/intellij/openshift/utils/odo/JSonParser.java
  src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCli.java
Labels: task, lgtm, approved, IC-2022.3

#884 fix: parse login command regexp and other regexp
  src/main/java/org/jboss/tools/intellij/openshift/telemetry/TelemetrySender.java
  src/main/java/org/jboss/tools/intellij/openshift/ui/cluster/TokenExtractor.java
  src/main/java/org/jboss/tools/intellij/openshift/ui/sandbox/CountryCodeValidator.java
  src/main/java/org/jboss/tools/intellij/openshift/ui/sandbox/PhoneNumberValidator.java
  src/main/java/org/jboss/tools/intellij/openshift/utils/OCCommandUtils.java
  src/test/java/org/jboss/tools/intellij/openshift/ui/cluster/TokenExtractorTest.java
  src/test/java/org/jboss/tools/intellij/openshift/ui/sandbox/CountryCodeValidatorTest.java
  src/test/java/org/jboss/tools/intellij/openshift/ui/sandbox/PhoneNumberValidatorTest.java
  src/test/java/org/jboss/tools/intellij/openshift/ui/sandbox/SandboxProcessorTest.java
  src/test/java/org/jboss/tools/intellij/openshift/utils/OCCommandUtilsTest.java
Labels: lgtm, approved
