Repository redhat-developer/intellij-openshift-connector, pull requests merged in 2024-04, with the labels that each got.

#750 fix: fix "Allowed roots should not contain '/'" assertion test error
  src/test/java/org/jboss/tools/intellij/openshift/validation/DevfileSchemasTest.java
Labels: lgtm, approved

#766 refactor: Use IDEATrustManager class from common
  build.gradle
  src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCli.java
  src/main/resources/META-INF/plugin.xml
Labels: lgtm, approved

#777 fix: rm'd explicit snakeyaml dependency causing fatal IDE error (#776)
  build.gradle
Labels: lgtm, approved

#778 chore(skip-release): bump sinceIdea to IC-2022.3
  .github/workflows/validate_IJ_versions.yml
  build.gradle
  gradle.properties
  src/main/resources/META-INF/plugin.xml
Labels: lgtm, approved

#781 chore: Update devfile schema from 2.0.0 to 2.2.2
  src/main/resources/schemas/devfile.json
Labels: lgtm, approved, needs-ok-to-test

#792 fix: revert the choice to publish version to marketplace
  .github/workflows/release.yml
Labels: lgtm, approved

#759 refactor: bump openshift-client 6.12 (#758)
  build.gradle
Labels: lgtm, approved

#793 fix: corrected intellij-common for test (#758)
  build.gradle
Labels: lgtm, approved

#786 chore(skip-release): Prepare 1.9.0
  gradle.properties
  src/main/resources/META-INF/plugin.xml
Labels: lgtm, approved

#805 fix: fix Integration tests
  src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliComponentTest.java
  src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliTest.java
  src/it/projects/nodejs/.gitignore
  src/it/projects/nodejs/LICENSE
  src/it/projects/nodejs/README.md
  src/it/projects/nodejs/package-lock.json
  src/it/projects/nodejs/package.json
  src/it/projects/nodejs/server.js
  src/it/projects/nodejs/test/test.js
  src/test/java/org/jboss/tools/intellij/openshift/validation/DevfileSchemasTest.java
  src/test/resources/devfiles/java-quarkus-v200.yaml
  src/test/resources/devfiles/sample-python-v220.yaml
Labels: lgtm, approved

#801 chore(skip-release): corrected action label capitalizations
  src/main/resources/META-INF/plugin.xml
Labels: enhancement, lgtm, approved

#796 fix: Update helm to 3.13.2
  src/main/resources/tools.json
Labels: lgtm, approved

#804 fix: 'Delete Project' label is confusing when using kubernetes cluster
  src/main/java/org/jboss/tools/intellij/openshift/actions/project/DeleteProjectAction.java
Labels: lgtm, approved
