Repository redhat-developer/intellij-openshift-connector, pull requests merged in 2024-09, with the labels that each got.

#911 chore(skip-release): bump intellij common 1.9.6
  build.gradle
Labels: task, lgtm, approved

#880 fix: fix name validation regexp
  src/main/java/org/jboss/tools/intellij/openshift/ui/project/CreateNewProjectDialog.java
Labels: lgtm, approved

#913 fix: corrected widget alignements in install helm chart panel (#876)
  src/main/java/org/jboss/tools/intellij/openshift/ui/helm/install/InstallPanel.java
Labels: lgtm, approved

#877 chore(skip-release): resized images
  images/1.10.0/helm-add-dialog.png
  images/1.10.0/helm-chart-install-validation.png
  images/1.10.0/helm-chart-install.png
  images/1.10.0/helm-edit-dialog.png
  images/1.10.0/helm-edit.png
  images/1.10.0/helm-refresh.png
Labels: lgtm, approved

#830 chore(skip-release): Create dependency-submission workflow for project
  .github/workflows/dependency-submission.yml
Labels: task, dependencies

#915 fix: update tree, query cluster info and send telemetry in backgroud (#912)
  src/main/java/org/jboss/tools/intellij/openshift/WindowToolFactory.java
  src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationsRootNode.java
  src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationsTreeStructure.java
  src/main/java/org/jboss/tools/intellij/openshift/utils/Cli.java
  src/main/java/org/jboss/tools/intellij/openshift/utils/oc/OcCli.java
  src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCli.java
Labels: lgtm, approved

#919 fix: remove open console action.
  .gitignore
  src/main/java/org/jboss/tools/intellij/openshift/actions/cluster/OpenConsoleAction.java
  src/main/resources/META-INF/plugin.xml
  src/test/java/org/jboss/tools/intellij/openshift/actions/cluster/OpenConsoleActionTest.java
Labels: lgtm, approved

#918 test: use zipped projects
  src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliComponentTest.java
  src/it/projects/go.zip
  src/it/projects/go/.gitignore
  src/it/projects/go/README.md
  src/it/projects/go/go.mod
  src/it/projects/go/main.go
  src/it/projects/nodejs.zip
  src/it/projects/nodejs/.gitignore
  src/it/projects/nodejs/LICENSE
  src/it/projects/nodejs/README.md
  src/it/projects/nodejs/package-lock.json
  src/it/projects/nodejs/package.json
  src/it/projects/nodejs/server.js
  src/it/projects/nodejs/test/test.js
  src/it/projects/springboot-rest.zip
  src/it/projects/springboot-rest/.gitignore
  src/it/projects/springboot-rest/LICENSE
  src/it/projects/springboot-rest/README.adoc
  src/it/projects/springboot-rest/guide.adoc
  src/it/projects/springboot-rest/mvnw
  src/it/projects/springboot-rest/mvnw.cmd
  src/it/projects/springboot-rest/pom.xml
  src/it/projects/springboot-rest/src/licenses/contents/Apache+License+20
  src/it/projects/springboot-rest/src/licenses/contents/BSD+2clause+Simplified+License
  src/it/projects/springboot-rest/src/licenses/contents/Common+Development+and+Distribution+License+11
  src/it/projects/springboot-rest/src/licenses/contents/Common+Development+and+Distribution+License+CDDL+and+GNU+Public+License+v2+wClasspath+Exception
  src/it/projects/springboot-rest/src/licenses/contents/Eclipse+Public+License+Version+10
  src/it/projects/springboot-rest/src/licenses/contents/GNU+General+Public+License+Version+2+with+the+Classpath+Exception
  src/it/projects/springboot-rest/src/licenses/contents/GNU+Lesser+General+Public+License+v21+only
  src/it/projects/springboot-rest/src/licenses/contents/MIT+License
  src/it/projects/springboot-rest/src/licenses/contents/Mozilla+Public+License+11
  src/it/projects/springboot-rest/src/licenses/contents/Public+Domain
  src/it/projects/springboot-rest/src/licenses/contents/The+Asm+BSD+License
  src/it/projects/springboot-rest/src/licenses/licenses.html
  src/it/projects/springboot-rest/src/licenses/licenses.xml
  src/it/projects/springboot-rest/src/main/java/io/openshift/booster/BoosterApplication.java
  src/it/projects/springboot-rest/src/main/java/io/openshift/booster/service/Greeting.java
  src/it/projects/springboot-rest/src/main/java/io/openshift/booster/service/GreetingEndpoint.java
  src/it/projects/springboot-rest/src/main/resources/application.properties
  src/it/projects/springboot-rest/src/main/resources/static/index.html
  src/it/projects/springboot-rest/src/test/java/io/openshift/booster/AbstractBoosterApplicationTest.java
  src/it/projects/springboot-rest/src/test/java/io/openshift/booster/LocalTest.java
  src/it/projects/springboot-rest/src/test/java/io/openshift/booster/OpenShiftIT.java
  src/it/projects/springboot-rest/src/test/resources/arquillian.xml
  src/it/projects/springboot-rest/src/test/resources/logback-test.xml
Labels: lgtm, approved
